Tensor is a specialized multi-dimensional array designed for mathematical and computational efficiency.

- Scalars 
    - 0 dimensial tensor (a single number)
- Vectors 
    - 1 dimensioanl tensor (a list of numbers)
- Matrics
    - 2 dimensional tensors (a 2D grid of numbers)
- 3D Tensors
- 4D Tensors
    - Batches of RGB images
- 5D Tensors
    - Video data (adds a time dimension)


In [2]:
import torch as tr

In [3]:
x = tr.empty(2,2)                   # returns a tensor
y = tr.empty(3,2,2)
z = tr.empty(2,3,4,2)

print(x)
print('---------------------------------------------------------------')
print(y)
print('---------------------------------------------------------------')
print(z)

tensor([[-1.0466e+34,  1.2654e-42],
        [ 0.0000e+00,  0.0000e+00]])
---------------------------------------------------------------
tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])
---------------------------------------------------------------
tensor([[[[-1.0629e+34,  1.2654e-42],
          [ 0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00]],

         [[ 0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00]],

         [[ 0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00]]],


        [[[ 0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00]],

         [[ 0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,

In [4]:
print(type(z))
print(z.shape)
print(x.dtype)

<class 'torch.Tensor'>
torch.Size([2, 3, 4, 2])
torch.float32


In [5]:
# converting into numpy array

import numpy as np

temp = np.stack(y)

print(type(temp))
print(len(temp))

<class 'numpy.ndarray'>
3


In [6]:
temp

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]], dtype=float32)

#### Int and float datatype tensors

In [7]:
x = tr.ones(3,4, dtype=tr.int)
z = tr.ones(3,4, dtype=tr.float)


print(x)
print()
print(z)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [8]:
# making 1D tensor
print(tr.tensor([3,5]))

print()

# making 2D tensor
print(tr.tensor([
    [3,2],
    [5,2]
]))

tensor([3, 5])

tensor([[3, 2],
        [5, 2]])


In [9]:
# making random tensors in int
print(tr.randint(0,11, (3,2)))              # 0, and 11 is choosing the numbers btwn 0 and 10
print()
print(tr.randint(0,10,(2,3,4)))

tensor([[2, 6],
        [1, 3],
        [2, 8]])

tensor([[[9, 3, 6, 0],
         [7, 1, 7, 6],
         [0, 9, 1, 5]],

        [[8, 3, 7, 1],
         [9, 2, 5, 9],
         [3, 5, 9, 0]]])


In [10]:
# making random tensors in float
print(tr.rand(5,2))                 # does not take datatype as int
print()
print(tr.rand(2,5,3))

tensor([[0.1964, 0.4621],
        [0.3361, 0.6700],
        [0.3305, 0.4062],
        [0.7981, 0.6931],
        [0.4586, 0.2949]])

tensor([[[0.8246, 0.9488, 0.8879],
         [0.0414, 0.2743, 0.6729],
         [0.8078, 0.4926, 0.9564],
         [0.4999, 0.3975, 0.1427],
         [0.4388, 0.6236, 0.5395]],

        [[0.2569, 0.9677, 0.1900],
         [0.3861, 0.8784, 0.9862],
         [0.7546, 0.0196, 0.8764],
         [0.6581, 0.6204, 0.9861],
         [0.0634, 0.4860, 0.1928]]])


In [11]:
x = tr.rand(2,5,3)
y = tr.rand(2,5,3)

In [12]:
print(x)
print('------------------------------------------------')
print(y)
print('------------------------------------------------')

tensor([[[0.2443, 0.7330, 0.8733],
         [0.6736, 0.6815, 0.0715],
         [0.3935, 0.0467, 0.8586],
         [0.7738, 0.8417, 0.8052],
         [0.5022, 0.8643, 0.5404]],

        [[0.5820, 0.1569, 0.1639],
         [0.0301, 0.7369, 0.5153],
         [0.9177, 0.3169, 0.9384],
         [0.4697, 0.1200, 0.9385],
         [0.1961, 0.1498, 0.7476]]])
------------------------------------------------
tensor([[[0.4616, 0.2213, 0.8501],
         [0.5913, 0.9088, 0.3063],
         [0.6749, 0.3475, 0.7771],
         [0.0290, 0.7138, 0.4565],
         [0.2725, 0.2042, 0.0575]],

        [[0.9204, 0.1827, 0.3599],
         [0.8369, 0.5449, 0.4265],
         [0.6411, 0.1691, 0.8019],
         [0.3687, 0.0916, 0.0092],
         [0.7500, 0.4941, 0.3462]]])
------------------------------------------------


In [13]:
print(x + y)
print('------------------------------------------------')
print(x + 4)

tensor([[[0.7058, 0.9543, 1.7234],
         [1.2649, 1.5903, 0.3779],
         [1.0684, 0.3943, 1.6358],
         [0.8028, 1.5555, 1.2616],
         [0.7747, 1.0685, 0.5979]],

        [[1.5024, 0.3395, 0.5238],
         [0.8670, 1.2818, 0.9418],
         [1.5588, 0.4860, 1.7403],
         [0.8384, 0.2116, 0.9477],
         [0.9460, 0.6439, 1.0937]]])
------------------------------------------------
tensor([[[4.2443, 4.7330, 4.8733],
         [4.6736, 4.6815, 4.0715],
         [4.3935, 4.0467, 4.8586],
         [4.7738, 4.8417, 4.8052],
         [4.5022, 4.8643, 4.5404]],

        [[4.5820, 4.1569, 4.1639],
         [4.0301, 4.7369, 4.5153],
         [4.9177, 4.3169, 4.9384],
         [4.4697, 4.1200, 4.9385],
         [4.1961, 4.1498, 4.7476]]])


#### Reshaping the tensors

In [14]:
x = tr.randint(0,10,(3,3,4))
print(x)
print('--------------------------------------------')
print()

# making a 1D tensor
print(x.view(-1))
print('--------------------------------------------')
print()

# making a 2D tensor
print(x.view(-1, 36))
print('--------------------------------------------')
print()

# 2D tensor containing 3 rows
print(x.view(3, -1))

tensor([[[9, 7, 6, 8],
         [2, 6, 7, 4],
         [8, 4, 3, 4]],

        [[0, 2, 0, 5],
         [3, 7, 7, 6],
         [4, 3, 7, 5]],

        [[4, 5, 4, 4],
         [1, 6, 6, 5],
         [6, 4, 0, 9]]])
--------------------------------------------

tensor([9, 7, 6, 8, 2, 6, 7, 4, 8, 4, 3, 4, 0, 2, 0, 5, 3, 7, 7, 6, 4, 3, 7, 5,
        4, 5, 4, 4, 1, 6, 6, 5, 6, 4, 0, 9])
--------------------------------------------

tensor([[9, 7, 6, 8, 2, 6, 7, 4, 8, 4, 3, 4, 0, 2, 0, 5, 3, 7, 7, 6, 4, 3, 7, 5,
         4, 5, 4, 4, 1, 6, 6, 5, 6, 4, 0, 9]])
--------------------------------------------

tensor([[9, 7, 6, 8, 2, 6, 7, 4, 8, 4, 3, 4],
        [0, 2, 0, 5, 3, 7, 7, 6, 4, 3, 7, 5],
        [4, 5, 4, 4, 1, 6, 6, 5, 6, 4, 0, 9]])
