# **PyTorch Basics**

In [31]:
import torch as tr
import numpy as np

In [32]:
print(tr.__version__)

2.11.0+cu128


In [33]:
if tr.cuda.is_available():
    print('GPU IS AVAILABLE')
    print(f'USING GPU : {tr.cuda.get_device_name(0)}')
else:
    print('GPU NOT AVAILABLE')

GPU IS AVAILABLE
USING GPU : Tesla T4


In [34]:
print(tr.arange(0,11, 2))                             # same as np.arange
print(tr.arange(0,11))

tensor([ 0,  2,  4,  6,  8, 10])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


In [35]:
print(tr.linspace(1,10, 20))                        # making 20 numbers btwn 1 to 10 while every number being evenly spaced, same as np.linspace

tensor([ 1.0000,  1.4737,  1.9474,  2.4211,  2.8947,  3.3684,  3.8421,  4.3158,
         4.7895,  5.2632,  5.7368,  6.2105,  6.6842,  7.1579,  7.6316,  8.1053,
         8.5789,  9.0526,  9.5263, 10.0000])


In [36]:
print(tr.eye(5))
print()
print(tr.eye(5,2))

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

tensor([[1., 0.],
        [0., 1.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


In [37]:
x = tr.randint(0,11, (3,5))
print(x.shape)
print(x.size)

torch.Size([3, 5])
<built-in method size of Tensor object at 0x7b2a55ae0640>


In [41]:
x = tr.rand(5,3)
print(x)
print()
print(tr.mean(x))                  # returns mean of all numbers in the matrics
print(tr.mean(x, dim=0))          # mean of all columns
print(tr.mean(x, dim=1))          # mean of all rows

tensor([[0.1402, 0.4991, 0.6338],
        [0.1274, 0.7083, 0.8483],
        [0.3441, 0.8918, 0.6256],
        [0.3560, 0.2789, 0.0946],
        [0.7149, 0.8564, 0.8138]])

tensor(0.5289)
tensor([0.3365, 0.6469, 0.6032])
tensor([0.4243, 0.5613, 0.6205, 0.2432, 0.7950])


In [44]:
print(tr.median(x))
print()
print(tr.median(x, dim=0))
print()
print(tr.median(x, dim=1))

tensor(0.6256)

torch.return_types.median(
values=tensor([0.3441, 0.7083, 0.6338]),
indices=tensor([2, 1, 0]))

torch.return_types.median(
values=tensor([0.4991, 0.7083, 0.6256, 0.2789, 0.8138]),
indices=tensor([1, 1, 2, 1, 2]))


In [45]:
print(tr.max(x))
print()
print(tr.max(x, dim=0))
print()
print(tr.max(x, dim=1))

tensor(0.8918)

torch.return_types.max(
values=tensor([0.7149, 0.8918, 0.8483]),
indices=tensor([4, 2, 1]))

torch.return_types.max(
values=tensor([0.6338, 0.8483, 0.8918, 0.3560, 0.8564]),
indices=tensor([2, 2, 1, 0, 1]))


In [46]:
print(tr.min(x))
print()
print(tr.min(x, dim=0))
print()
print(tr.min(x, dim=1))

tensor(0.0946)

torch.return_types.min(
values=tensor([0.1274, 0.2789, 0.0946]),
indices=tensor([1, 3, 3]))

torch.return_types.min(
values=tensor([0.1402, 0.1274, 0.3441, 0.0946, 0.7149]),
indices=tensor([0, 0, 0, 2, 0]))


In [47]:
print(tr.std(x))             # standard deviation
print()
print(tr.std(x, dim=0))
print()
print(tr.std(x, dim=1))

tensor(0.2851)

tensor([0.2376, 0.2573, 0.3019])

tensor([0.2551, 0.3823, 0.2739, 0.1343, 0.0726])


In [58]:
x = tr.rand(3)
y = tr.rand(3).T
print(x)
print()
print(y)
print()
print(tr.dot(x,y))            # remember is pytorch dot product is only limited to 1D tensors
# if you want to do dot product btwn 2D or 3D tensors, then you have to use "np.dot"

tensor([0.5339, 0.2514, 0.0209])

tensor([0.0815, 0.1609, 0.5335])

tensor(0.0951)


In [59]:
x = tr.rand(5,3)
y = tr.rand(5,3).T
print(x)
print()
print(y)
print()
print(np.dot(x,y))

tensor([[0.2063, 0.0409, 0.6326],
        [0.9310, 0.9475, 0.4538],
        [0.1012, 0.6335, 0.5081],
        [0.7835, 0.7999, 0.9196],
        [0.2714, 0.0980, 0.5514]])

tensor([[0.5481, 0.5431, 0.1376, 0.5548, 0.4407],
        [0.9435, 0.6714, 0.0653, 0.3659, 0.0583],
        [0.9358, 0.3066, 0.5756, 0.8147, 0.9261]])

[[0.7436648  0.33350748 0.39517295 0.6448436  0.6791735 ]
 [1.8289046  1.2810253  0.45121747 1.2329813  0.88579625]
 [1.1285654  0.6360678  0.34775835 0.70187473 0.55205595]
 [2.0447109  1.2446316  0.6893925  1.4766475  1.2435883 ]
 [0.7572306  0.38230094 0.361134   0.6357087  0.6360072 ]]


/tmp/ipykernel_48/3467203651.py:7: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  print(np.dot(x,y))


In [60]:
x = tr.rand(5,3)
y = tr.rand(5,3)
print(x)
print()
print(y)
print()
print(x > y)        # making comparison btwn elements

tensor([[0.2398, 0.0915, 0.7559],
        [0.8373, 0.2292, 0.1575],
        [0.2824, 0.9417, 0.3496],
        [0.4931, 0.4018, 0.4396],
        [0.4324, 0.3373, 0.4823]])

tensor([[0.6621, 0.0401, 0.0724],
        [0.9959, 0.7048, 0.8966],
        [0.2133, 0.9050, 0.7341],
        [0.3483, 0.4759, 0.0315],
        [0.8429, 0.6288, 0.4648]])

tensor([[False,  True,  True],
        [False, False, False],
        [ True,  True, False],
        [ True, False,  True],
        [False, False,  True]])


In [ ]:
print(x)
print()
print(tr.log(x))
print()
print(tr.exp(x))
print()
print(tr.sqrt(x))
print()
print(tr.sigmoid(x))
print()
print(tr.softmax(x, dim=0))
print()
print(tr.relu(x))

tensor([[0.2398, 0.0915, 0.7559],
        [0.8373, 0.2292, 0.1575],
        [0.2824, 0.9417, 0.3496],
        [0.4931, 0.4018, 0.4396],
        [0.4324, 0.3373, 0.4823]])

tensor([[-1.4280, -2.3917, -0.2798],
        [-0.1775, -1.4733, -1.8485],
        [-1.2643, -0.0601, -1.0511],
        [-0.7071, -0.9117, -0.8218],
        [-0.8385, -1.0866, -0.7292]])

tensor([[1.2710, 1.0958, 2.1296],
        [2.3102, 1.2576, 1.1705],
        [1.3264, 2.5642, 1.4184],
        [1.6373, 1.4946, 1.5521],
        [1.5409, 1.4012, 1.6198]])

tensor([[0.4897, 0.3025, 0.8694],
        [0.9151, 0.4787, 0.3968],
        [0.5314, 0.9704, 0.5912],
        [0.7022, 0.6339, 0.6631],
        [0.6575, 0.5808, 0.6945]])

tensor([[0.5597, 0.5229, 0.6805],
        [0.6979, 0.5570, 0.5393],
        [0.5701, 0.7194, 0.5865],
        [0.6208, 0.5991, 0.6082],
        [0.6064, 0.5835, 0.6183]])

tensor([[0.1572, 0.1402, 0.2699],
        [0.2857, 0.1609, 0.1483],
        [0.1640, 0.3282, 0.1798],
        [0.2025, 0.1913

#### Making inplace operation

In [75]:
x = tr.randint(0,10, (5,3))
y = tr.randint(0,10, (5,3))

print(x)
print()
print(y)
print()

x.add_(y)     # inplace operation is done to save memory usage

tensor([[6, 8, 8],
        [3, 2, 3],
        [0, 7, 0],
        [1, 9, 0],
        [3, 7, 1]])

tensor([[7, 2, 0],
        [6, 8, 3],
        [7, 7, 4],
        [4, 9, 5],
        [6, 0, 4]])



tensor([[13, 10,  8],
        [ 9, 10,  6],
        [ 7, 14,  4],
        [ 5, 18,  5],
        [ 9,  7,  5]])

In [78]:
# copying one tensor into another

print(x)
print()

temp = x.clone()

print(temp)

tensor([[13, 10,  8],
        [ 9, 10,  6],
        [ 7, 14,  4],
        [ 5, 18,  5],
        [ 9,  7,  5]])

tensor([[13, 10,  8],
        [ 9, 10,  6],
        [ 7, 14,  4],
        [ 5, 18,  5],
        [ 9,  7,  5]])
