# **PyTorch Basics**

In [1]:
import torch as tr
import numpy as np

In [2]:
print(tr.__version__)

2.11.0+cu128


In [3]:
if tr.cuda.is_available():
    print('GPU IS AVAILABLE')
    print(f'USING GPU : {tr.cuda.get_device_name(0)}')
else:
    print('GPU NOT AVAILABLE')

GPU IS AVAILABLE
USING GPU : Tesla T4


In [4]:
# making a tensor on gpu
device = tr.device('cuda')

x = tr.rand(5,3, device=device)
y = tr.rand(5,3, device=device)

print(x)
print()
print(y)

tensor([[0.0268, 0.4535, 0.4554],
        [0.5187, 0.2650, 0.3172],
        [0.7118, 0.7010, 0.3700],
        [0.6501, 0.2640, 0.2426],
        [0.6260, 0.0354, 0.4746]], device='cuda:0')

tensor([[0.4686, 0.1702, 0.6243],
        [0.6461, 0.0111, 0.9185],
        [0.4299, 0.9461, 0.4486],
        [0.9044, 0.7412, 0.6925],
        [0.5572, 0.9931, 0.6327]], device='cuda:0')


In [8]:
# sending a non-gpu tensor into gpu 
x = tr.rand(4,4)
print(x)
print()

temp = x.clone().to(device)                   # we use "to(device)" to add non-gpu tensor into the gpu
temp

tensor([[0.0416, 0.8376, 0.9457, 0.5600],
        [0.1956, 0.3046, 0.3012, 0.0643],
        [0.4576, 0.2464, 0.5394, 0.4772],
        [0.3537, 0.7288, 0.9014, 0.4819]])



tensor([[0.0416, 0.8376, 0.9457, 0.5600],
        [0.1956, 0.3046, 0.3012, 0.0643],
        [0.4576, 0.2464, 0.5394, 0.4772],
        [0.3537, 0.7288, 0.9014, 0.4819]], device='cuda:0')

#### Reshape

In [11]:
print(temp.flatten())
print()
print(temp.reshape(2,2,2,2))

tensor([0.0416, 0.8376, 0.9457, 0.5600, 0.1956, 0.3046, 0.3012, 0.0643, 0.4576,
        0.2464, 0.5394, 0.4772, 0.3537, 0.7288, 0.9014, 0.4819],
       device='cuda:0')

tensor([[[[0.0416, 0.8376],
          [0.9457, 0.5600]],

         [[0.1956, 0.3046],
          [0.3012, 0.0643]]],


        [[[0.4576, 0.2464],
          [0.5394, 0.4772]],

         [[0.3537, 0.7288],
          [0.9014, 0.4819]]]], device='cuda:0')
