In [1]:
import tensorflow as tf
import numpy as np

In [67]:
x = np.array(tf.random.uniform((5,4), minval=1, maxval=4, dtype=tf.int32))
y = np.array(tf.random.uniform((2,4), minval=4, maxval=9, dtype=tf.int32)).T


print(x)
print()
print(y)
print()
print()

np.dot(x,y)

[[2 3 3 2]
 [3 1 1 1]
 [2 3 1 2]
 [3 3 3 2]
 [1 1 2 1]]

[[4 5]
 [6 6]
 [4 7]
 [4 7]]




array([[46, 63],
       [26, 35],
       [38, 49],
       [50, 68],
       [22, 32]], dtype=int32)