In [1]:
import tensorflow as tf

In [62]:
x = tf.random.uniform((3,3), minval=1, maxval=11, dtype=tf.int32)
y = tf.random.normal((3,3), mean=0, stddev=1)

print(x)
print()
print(y)

tf.Tensor(
[[ 9  3  4]
 [ 3 10  1]
 [ 9  5  4]], shape=(3, 3), dtype=int32)

tf.Tensor(
[[-0.93217874 -0.19280212 -0.49387863]
 [ 0.55335623 -0.5414901  -0.9310321 ]
 [-0.43215984 -0.65283245 -0.2523522 ]], shape=(3, 3), dtype=float32)


In [126]:
print(tf.range((10), delta=2))
print()
print(tf.random.uniform((10,)))

tf.Tensor([0 2 4 6 8], shape=(5,), dtype=int32)

tf.Tensor(
[0.06051075 0.51626015 0.26688695 0.44112444 0.42240012 0.56039965
 0.58515024 0.66615677 0.2841494  0.40578544], shape=(10,), dtype=float32)


In [132]:
tf.ones((2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>