In [1]:
# Basically a tensor is a multidimensional array


import tensorflow as tf

### Creating a tensor

In [2]:
x = tf.constant(4)
print(x)

tf.Tensor(4, shape=(), dtype=int32)


In [8]:
x = tf.constant(4, shape=(1,1))
y = tf.constant(4, shape=(1,2))
z = tf.constant(4, shape=(1,3))
print(x)
print(y)
print(z)

tf.Tensor([[4]], shape=(1, 1), dtype=int32)
tf.Tensor([[4 4]], shape=(1, 2), dtype=int32)
tf.Tensor([[4 4 4]], shape=(1, 3), dtype=int32)


In [10]:
x = tf.constant(4, shape=(1,1))
y = tf.constant(4, shape=(2,1))
z = tf.constant(4, shape=(3,1))
print(x)
print()
print(y)
print()
print(z)

tf.Tensor([[4]], shape=(1, 1), dtype=int32)

tf.Tensor(
[[4]
 [4]], shape=(2, 1), dtype=int32)

tf.Tensor(
[[4]
 [4]
 [4]], shape=(3, 1), dtype=int32)


In [11]:
print(tf.constant(0, shape=(5,10)))

tf.Tensor(
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]], shape=(5, 10), dtype=int32)


In [19]:
print(tf.constant(0, shape=(5,2,3)))

tf.Tensor(
[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]], shape=(5, 2, 3), dtype=int32)


In [23]:
print(tf.constant([[1,2,3], [4,5,6], [7,8,9], [2,6,7]]))

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [2 6 7]], shape=(4, 3), dtype=int32)


In [25]:
print(tf.constant([[[1,2,3], [4,5,6], [7,8,9], [2,6,7]], [[1,2,3], [4,5,6], [7,8,9], [2,6,7]]]))

tf.Tensor(
[[[1 2 3]
  [4 5 6]
  [7 8 9]
  [2 6 7]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]
  [2 6 7]]], shape=(2, 4, 3), dtype=int32)


In [35]:
print(tf.zeros((3,3)))
print()
print(tf.ones((4,3)))

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(4, 3), dtype=float32)


In [ ]:
print(tf.eye(4))            # identity matrix

tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]], shape=(4, 4), dtype=float32)


In [ ]:
print(tf.random.normal((3,3)))          # Generates a 3x3 tensor of random numbers from a normal distribution

tf.Tensor(
[[ 0.71715504  0.35122666 -2.9535356 ]
 [-1.6394864   0.08114444  1.3224232 ]
 [-0.13909483  1.3111267   0.3869781 ]], shape=(3, 3), dtype=float32)


In [169]:
print(tf.random.uniform((3,3),  minval=0, maxval=1))

tf.Tensor(
[[0.4177338  0.45667684 0.17915559]
 [0.7764616  0.5714359  0.37216914]
 [0.64217424 0.5962609  0.9025371 ]], shape=(3, 3), dtype=float32)


In [ ]:
print(tf.random.normal((3,3), mean=0, stddev=1))           # Generates a 3x3 tensor while explicitly defining the mean as 0 and stddev (standard deviation) as 1

tf.Tensor(
[[ 0.48818958 -0.6573537  -0.08465921]
 [-0.9030656   0.15824291  0.9607436 ]
 [ 1.9372132  -0.43807125  0.5678239 ]], shape=(3, 3), dtype=float32)


In [166]:
print(tf.random.uniform((3,3), minval=0, maxval=1))

tf.Tensor(
[[0.21584606 0.47714722 0.9243212 ]
 [0.01276159 0.10966456 0.16994512]
 [0.29574037 0.06509805 0.8850776 ]], shape=(3, 3), dtype=float32)


| Feature | `tf.random.uniform` | `tf.random.normal` |
| :--- | :--- | :--- |
| **Distribution Shape** | Flat (Equal probability) | Bell Curve (Gaussian) |
| **Key Parameters** | `minval`, `maxval` | `mean`, `stddev` (Standard Deviation) |
| **Defaults** | Range `[0, 1)` | Mean `0.0`, StdDev `1.0` |
| **Bounds** | Strictly bounded (never exceeds min/max) | Unbounded (can theoretically produce any number) |

In [ ]:
tf.range(start=2, limit=10, delta=2)            
# start -- start of number
# limit -- end of number
# delta -- difference btwn numbers

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 4, 6, 8], dtype=int32)>

In [181]:
tf.range(2,10,2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 4, 6, 8], dtype=int32)>

In [172]:
print(tf.range(9))

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
