In [1]:
import tensorflow as tf

In [79]:
x = tf.random.uniform((3,3), minval=1, maxval=10)
y = tf.random.uniform((3,3), minval=5, maxval=15)

print(x)
print()
print(y)

tf.Tensor(
[[4.895711  2.790103  3.3280673]
 [2.7300925 3.552169  1.0431203]
 [8.146922  1.1210052 5.6505933]], shape=(3, 3), dtype=float32)

tf.Tensor(
[[ 7.4388065 14.580938   5.372162 ]
 [10.638313  14.450608  11.430107 ]
 [12.984711   7.216432  13.082535 ]], shape=(3, 3), dtype=float32)


In [81]:
print(x + y)
print()
print(tf.add(x,y))

tf.Tensor(
[[12.3345175 17.37104    8.70023  ]
 [13.368406  18.002777  12.4732275]
 [21.131634   8.337438  18.733128 ]], shape=(3, 3), dtype=float32)

tf.Tensor(
[[12.3345175 17.37104    8.70023  ]
 [13.368406  18.002777  12.4732275]
 [21.131634   8.337438  18.733128 ]], shape=(3, 3), dtype=float32)


In [ ]:
print(x - y)
print()
print(x * y)            # only does element wise multiplication, not matrix multiplication
print()
print(x / y)            # division
print()
print(x // y)           # floor division

tf.Tensor(
[[ -2.5430956 -11.790835   -2.0440946]
 [ -7.908221  -10.898439  -10.386987 ]
 [ -4.8377886  -6.095427   -7.4319415]], shape=(3, 3), dtype=float32)

tf.Tensor(
[[ 36.418247   40.68232    17.878916 ]
 [ 29.04358    51.331005   11.9229765]
 [105.78542     8.089658   73.92408  ]], shape=(3, 3), dtype=float32)

tf.Tensor(
[[0.65813124 0.19135277 0.6195024 ]
 [0.25662833 0.2458145  0.09126076]
 [0.62742424 0.15534064 0.43191883]], shape=(3, 3), dtype=float32)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [116]:
# matrix multiplication
print(x @ y)
print()
print(tf.matmul(x,y))
print()
print(np.matmul(x,y))

tf.Tensor(
[[109.314224 135.71951  101.731285]
 [ 71.642334  98.665924  68.91483 ]
 [145.9003   175.76611  130.50388 ]], shape=(3, 3), dtype=float32)

tf.Tensor(
[[109.314224 135.71951  101.731285]
 [ 71.642334  98.665924  68.91483 ]
 [145.9003   175.76611  130.50388 ]], shape=(3, 3), dtype=float32)

[[109.314224 135.71951  101.731285]
 [ 71.642334  98.66592   68.91483 ]
 [145.9003   175.76611  130.50388 ]]


In [ ]:
import numpy as np
print(np.dot(x,y))                  # dot product
print()
print(tf.tensordot(x,y, axes=1))    # dot product


[[109.314224 135.71951  101.731285]
 [ 71.642334  98.66592   68.91483 ]
 [145.9003   175.76611  130.50388 ]]

tf.Tensor(
[[109.314224 135.71951  101.731285]
 [ 71.642334  98.665924  68.91483 ]
 [145.9003   175.76611  130.50388 ]], shape=(3, 3), dtype=float32)


In [ ]:
print(tf.reduce_sum(x*y))
print()
print(tf.tensordot(x,y, axes=2))
print()
print(tf.tensordot(x,y, axes=1))
print()
print(tf.reduce_sum(x*y, axis=0))
print()
print(tf.reduce_sum(x*y, axis=1))

tf.Tensor(375.0762, shape=(), dtype=float32)

tf.Tensor(375.0762, shape=(), dtype=float32)

tf.Tensor(
[[109.314224 135.71951  101.731285]
 [ 71.642334  98.665924  68.91483 ]
 [145.9003   175.76611  130.50388 ]], shape=(3, 3), dtype=float32)

tf.Tensor([171.24725 100.10298 103.72597], shape=(3,), dtype=float32)

tf.Tensor([ 94.979485  92.29756  187.79916 ], shape=(3,), dtype=float32)


In [112]:
print(x)
print()
print(x * 2)
print()
print(x ** 2)

tf.Tensor(
[[4.895711  2.790103  3.3280673]
 [2.7300925 3.552169  1.0431203]
 [8.146922  1.1210052 5.6505933]], shape=(3, 3), dtype=float32)

tf.Tensor(
[[ 9.791422   5.580206   6.6561346]
 [ 5.460185   7.104338   2.0862405]
 [16.293844   2.2420104 11.301187 ]], shape=(3, 3), dtype=float32)

tf.Tensor(
[[23.967985   7.784674  11.076032 ]
 [ 7.453405  12.617905   1.0880998]
 [66.37234    1.2566526 31.929205 ]], shape=(3, 3), dtype=float32)


In [113]:
tf.matmul(x,y)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[109.314224, 135.71951 , 101.731285],
       [ 71.642334,  98.665924,  68.91483 ],
       [145.9003  , 175.76611 , 130.50388 ]], dtype=float32)>