In [1]:
import tensorflow as tf

In [2]:
# creating 1D tensor
x = tf.random.uniform((10,), minval=1, maxval=11, dtype=tf.int32)
x

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([1, 4, 7, 1, 2, 9, 7, 5, 6, 7], dtype=int32)>

In [3]:
print(x[:])
print()
print(x[1:5])
print()
print(x[-1])

tf.Tensor([1 4 7 1 2 9 7 5 6 7], shape=(10,), dtype=int32)

tf.Tensor([4 7 1 2], shape=(4,), dtype=int32)

tf.Tensor(7, shape=(), dtype=int32)


In [5]:
print(x[::2])                   # printing one element, skipping next and so on
print()
print(x[::-1])                  # printing reversed

tf.Tensor([1 7 2 7 6], shape=(5,), dtype=int32)

tf.Tensor([7 6 5 7 9 2 1 7 4 1], shape=(10,), dtype=int32)


In [47]:
x = tf.random.uniform((3,3,5), minval=1, maxval=10, dtype=tf.int32)
x

<tf.Tensor: shape=(3, 3, 5), dtype=int32, numpy=
array([[[1, 5, 8, 9, 2],
        [2, 3, 7, 4, 5],
        [1, 6, 6, 6, 3]],

       [[7, 6, 4, 8, 2],
        [1, 6, 8, 4, 6],
        [7, 1, 6, 8, 4]],

       [[9, 6, 6, 4, 8],
        [4, 5, 3, 1, 4],
        [7, 2, 3, 7, 7]]], dtype=int32)>

In [72]:
print(x[0])
print()
print(x[1])
print()
print(x[0, 0])
print(x[0, 1])
print()
print(x[1,1,:4])
print(x[1,1,2])
print(x[1,1,-1])
print()

tf.Tensor(
[[1 5 8 9 2]
 [2 3 7 4 5]
 [1 6 6 6 3]], shape=(3, 5), dtype=int32)

tf.Tensor(
[[7 6 4 8 2]
 [1 6 8 4 6]
 [7 1 6 8 4]], shape=(3, 5), dtype=int32)

tf.Tensor([1 5 8 9 2], shape=(5,), dtype=int32)
tf.Tensor([2 3 7 4 5], shape=(5,), dtype=int32)

tf.Tensor([1 6 8 4], shape=(4,), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)



In [80]:
x = tf.reshape(tf.range(12), (3,4))
x

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)>

In [85]:
import numpy as np

print(tf.transpose(x))
print()
print(tf.transpose(x, perm=[1,0]))
print()
print(np.transpose(x))

tf.Tensor(
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]], shape=(4, 3), dtype=int32)

tf.Tensor(
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]], shape=(4, 3), dtype=int32)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
