In [1]:
import tensorflow as tf

In [62]:
# creating 1D tensor
x = tf.random.uniform((10,), minval=1, maxval=11, dtype=tf.int32)
x

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([5, 9, 9, 5, 4, 4, 2, 2, 8, 8], dtype=int32)>

In [64]:
print(x[:])
print()
print(x[1:5])
print()
print(x[-1])

tf.Tensor([5 9 9 5 4 4 2 2 8 8], shape=(10,), dtype=int32)

tf.Tensor([9 9 5 4], shape=(4,), dtype=int32)

tf.Tensor(8, shape=(), dtype=int32)
